/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DTO.LoaiMonAn;
import DTO.MonAn;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luu Quang Khai
 */
public class QuanLyMonAn extends javax.swing.JInternalFrame {

    ArrayList<MonAn> dsMonAn = new ArrayList<>();
    ArrayList<LoaiMonAn> dsLoaiMonAn = new ArrayList<>();
    
    /**
     * Creates new form QuanLyMonAn
     */
    public QuanLyMonAn() {
        initComponents();
        
        layDanhSachLoaiMonAn();
        hienThiLoaiMonAn();
        
        layDanhSachMonAn();
        hienThiMonAn();
        
        this.cboMaLoaiMonAn.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listLoaiMonAn = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnThemLoaiMonAn = new javax.swing.JButton();
        btnXoaLoaiMonAn = new javax.swing.JButton();
        btnSuaLoaiMonAn = new javax.swing.JButton();
        txtMaLoai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTimKiemMonAn = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txtMaMonAn = new javax.swing.JTextField();
        txtTenMonAn = new javax.swing.JTextField();
        txtGiaTien = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cboMaLoaiMonAn = new javax.swing.JComboBox<>();
        btnThemMonAn = new javax.swing.JButton();
        btnXoaMonAn = new javax.swing.JButton();
        btnSuaMonAn = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();

        setResizable(true);
        setMaximumSize(new java.awt.Dimension(974, 573));
        setMinimumSize(new java.awt.Dimension(974, 573));
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Quản lý món ăn");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách món ăn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giá tiền", "Tồn kho"
            }
        ));
        tblMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonAnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonAn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Loại món ăn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        listLoaiMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        listLoaiMonAn.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listLoaiMonAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLoaiMonAnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listLoaiMonAn);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên loại:");

        btnThemLoaiMonAn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemLoaiMonAn.setText("Thêm");
        btnThemLoaiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiMonAnActionPerformed(evt);
            }
        });

        btnXoaLoaiMonAn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoaLoaiMonAn.setText("Xóa");
        btnXoaLoaiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiMonAnActionPerformed(evt);
            }
        });

        btnSuaLoaiMonAn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuaLoaiMonAn.setText("Sửa");
        btnSuaLoaiMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiMonAnActionPerformed(evt);
            }
        });

        txtMaLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaLoai.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã loại:");

        txtTenLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTenLoaiMouseClicked(evt);
            }
        });
        txtTenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLoai)
                            .addComponent(txtTenLoai)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnThemLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSuaLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mã món ăn:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tên món ăn:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Giá tiền:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Số lượng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        txtTimKiemMonAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        txtMaMonAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaMonAn.setEnabled(false);

        txtTenMonAn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtGiaTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Mã loại:");

        cboMaLoaiMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cboMaLoaiMonAn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnThemMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMonAn.setText("Thêm");
        btnThemMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonAnActionPerformed(evt);
            }
        });

        btnXoaMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaMonAn.setText("Xóa");
        btnXoaMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMonAnActionPerformed(evt);
            }
        });

        btnSuaMonAn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaMonAn.setText("Sửa");
        btnSuaMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaMonAnActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(42, 42, 42)
                                .addComponent(txtTenMonAn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaMonAn)
                                    .addComponent(cboMaLoaiMonAn, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(70, 70, 70)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaTien)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTimKiemMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(61, 61, 61)
                                .addComponent(txtSoLuong)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnXoaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnThemMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSuaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(153, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTimKiem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLamMoi)
                                .addGap(14, 14, 14))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cboMaLoaiMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtMaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTenMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTimKiemMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTimKiem)
                                    .addComponent(btnLamMoi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnThemMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnXoaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSuaMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listLoaiMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLoaiMonAnMouseClicked
        // TODO add your handling code here:
        int n = this.listLoaiMonAn.getSelectedIndex();
        if(n != -1)
        {
            LoaiMonAn x = dsLoaiMonAn.get(n);
            this.txtMaLoai.setText(String.valueOf(x.getMaLoaiMonAn()));
            this.txtTenLoai.setText(x.getTenLoaiMonAn());
        }
    }//GEN-LAST:event_listLoaiMonAnMouseClicked

    private void btnThemLoaiMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiMonAnActionPerformed
        // TODO add your handling code here:
        if(this.txtTenLoai.getText().trim().equals(""))
        {
            thongBao("Vui lòng nhập: Tên loại món ăn!");
        }
        else
        {
            DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
            int n = dao.kiemTraLoaiMonAn(this.txtTenLoai.getText().trim());
            if(n == 1)
            {
                thongBao("Tên loại: " + this.txtTenLoai.getText().trim() + " đã tồn tại!");
            }
            else
            {
                int x = dao.themLoaiMonAn(this.txtTenLoai.getText().trim());
                if(x == -1)
                {
                    thongBao("Lỗi thêm loại món ăn!");
                }
                else
                {
                    thongBao("Thêm thành công.");
                    layDanhSachLoaiMonAn();
                    hienThiLoaiMonAn();
                    this.txtMaLoai.setText("");
                    this.txtTenLoai.setText("");
                    this.listLoaiMonAn.clearSelection();
                }
            }
            
        }
    }//GEN-LAST:event_btnThemLoaiMonAnActionPerformed

    private void btnXoaLoaiMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiMonAnActionPerformed
        // TODO add your handling code here:
        if(this.txtTenLoai.getText().trim().equals(""))
        {
            thongBao("Vui lòng nhập tên loại cần xóa!");
        }
        else
        {
            DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
            int b = dao.kiemTraLoaiMonAn(this.txtTenLoai.getText().trim());
            if(b == 1)
            {
                int k = thongBaoXacNhan("Xóa " + this.txtTenLoai.getText() + " khỏi danh sách.");
                if(k == JOptionPane.YES_OPTION)
                {
                    int h = dao.xoaLoaiMonAn(this.txtTenLoai.getText());
                    if(h == -1)
                        thongBao("Xóa không thành công!");
                    else
                    {
                        thongBao("Xóa thành công.");
                        layDanhSachLoaiMonAn();
                        hienThiLoaiMonAn();
                        this.txtMaLoai.setText("");
                        this.txtTenLoai.setText("");
                        this.listLoaiMonAn.clearSelection();
                    }
                }
            }
            else
            {
                thongBao("Tên loại: " + this.txtTenLoai.getText() + " không tồn tại!");
            }
        }
    }//GEN-LAST:event_btnXoaLoaiMonAnActionPerformed

    private void btnSuaLoaiMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiMonAnActionPerformed
        // TODO add your handling code here:
        int n = this.listLoaiMonAn.getSelectedIndex();
        if(n == -1)
        {
            thongBao("Chọn loại món ăn trên bảng để sửa!");
        }
        else
        {
            int t = thongBaoXacNhan("Bạn có muốn sửa tên loại: " + this.listLoaiMonAn.getSelectedValue() + " thành " + this.txtTenLoai.getText().trim());
            if(t == JOptionPane.YES_OPTION)
            {
                DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
                DTO.LoaiMonAn dto = new DTO.LoaiMonAn(Integer.valueOf(this.txtMaLoai.getText()),this.txtTenLoai.getText().trim());
                int k = dao.suaLoaiMonAn(dto);
                if(k == -1)
                {
                    thongBao("Sửa không thành công!");
                }
                else
                {
                    thongBao("Đã sửa tên loại thành " +this.txtTenLoai.getText().trim() +".");
                    layDanhSachLoaiMonAn();
                    hienThiLoaiMonAn();
                    this.txtMaLoai.setText("");
                    this.txtTenLoai.setText("");
                }
            }
        }
        
        
    }//GEN-LAST:event_btnSuaLoaiMonAnActionPerformed

    private void txtTenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiActionPerformed

    private void txtTenLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenLoaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiMouseClicked

    private void btnThemMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonAnActionPerformed
        // TODO add your handling code here:
        int n = this.cboMaLoaiMonAn.getSelectedIndex();
        if( n == -1)
        {
            thongBao("Phải chọn loại món ăn!");
        }
        else
        {
            if(this.txtTenMonAn.getText().trim().equals("") || this.txtGiaTien.getText().trim().equals("") || this.txtSoLuong.getText().trim().equals(""))    
            {
                thongBao("Phải nhập đầy đủ thông tin!");
            }
            else
            {
                int t = thongBaoXacNhan("Bạn có chắc chắn thêm món ăn?");
                if(t == JOptionPane.YES_OPTION)
                {
                    try
                    {
                        float giaTien = Float.valueOf(this.txtGiaTien.getText().trim());
                        int soLuong = Integer.valueOf(this.txtSoLuong.getText().trim());
                        DTO.MonAn dto = new DTO.MonAn();
                        dto.setTenMonAn(this.txtTenMonAn.getText().trim());
                        dto.setGiaTien(giaTien);
                        dto.setSoLuong(soLuong);
                        LoaiMonAn x = dsLoaiMonAn.get(this.cboMaLoaiMonAn.getSelectedIndex());
                        dto.setMaLoaiMon(x.getMaLoaiMonAn());
                        DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
                        int y = dao.themMonAn(dto);
                        if(y == -1)
                        {
                            thongBao("Thêm món ăn không thành công");
                        }
                        else
                        {
                            thongBao("Đã thêm món ăn.");
                            layDanhSachMonAn();
                            hienThiMonAn();
                            lamMoi();
                        }
                    }
                    catch(Exception ex)
                    {
                        thongBao("Giá tiền và số lượng chỉ được nhập kí tự số!");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnThemMonAnActionPerformed

    private void tblMonAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonAnMouseClicked
        // TODO add your handling code here:
        int n = this.tblMonAn.getSelectedRow();
        MonAn y = dsMonAn.get(n);
        this.txtMaMonAn.setText(String.valueOf(y.getMaMonAn()));
        this.txtTenMonAn.setText(y.getTenMonAn());
        this.txtGiaTien.setText(String.valueOf(y.getGiaTien()));
        this.txtSoLuong.setText(String.valueOf(y.getSoLuong()));
        for(int i = 0; i < dsLoaiMonAn.size(); i++)
        {
            LoaiMonAn x = dsLoaiMonAn.get(i);
            if(x.getMaLoaiMonAn() == y.getMaLoaiMon())
            {
                this.cboMaLoaiMonAn.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_tblMonAnMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        lamMoi();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnXoaMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMonAnActionPerformed
        // TODO add your handling code here:
        int n = this.tblMonAn.getSelectedRow();
        if(n == -1)
        {
            thongBao("Hãy chọn món ăn cần xóa trên danh sách để xóa!");
        }
        else
        {
            int t = thongBaoXacNhan("Xóa món ăn?");
            if(t == JOptionPane.YES_OPTION)
            {
                DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
                int k = dao.xoaMonAn(Integer.valueOf(this.txtMaMonAn.getText()));
                if(k == -1)
                {
                    thongBao("Xóa thất bại!");
                }
                else
                {
                    thongBao("Xóa thành công.");
                    lamMoi();
                    layDanhSachMonAn();
                    hienThiMonAn();
                }
            }
        }
    }//GEN-LAST:event_btnXoaMonAnActionPerformed

    private void btnSuaMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaMonAnActionPerformed
        // TODO add your handling code here:
        int n = this.tblMonAn.getSelectedRow();
        if(n == -1)
        {
            thongBao("Hãy chọn món ăn cần sửa trên table.");
        }
        else
        {
            if(this.txtTenMonAn.getText().trim().equals("") || this.txtGiaTien.getText().trim().equals("") || this.txtSoLuong.getText().trim().equals(""))    
            {
                thongBao("Phải nhập đầy đủ thông tin!");
            }
            else
            {
                int t = thongBaoXacNhan("Thay đổi dữ thông tin?");
                if(t == JOptionPane.YES_OPTION)
                {
                    try
                    {
                        float giaTien = Float.valueOf(this.txtGiaTien.getText().trim());
                        int soLuong = Integer.valueOf(this.txtSoLuong.getText().trim());
                        DTO.MonAn dto = new DTO.MonAn();
                        dto.setTenMonAn(this.txtTenMonAn.getText().trim());
                        dto.setGiaTien(giaTien);
                        dto.setSoLuong(soLuong);
                        LoaiMonAn x = dsLoaiMonAn.get(this.cboMaLoaiMonAn.getSelectedIndex());
                        dto.setMaLoaiMon(x.getMaLoaiMonAn());
                        dto.setMaMonAn(Integer.valueOf(this.txtMaMonAn.getText()));
                        DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
                        int y = dao.suaMonAn(dto);
                        if(y == -1)
                        {
                            thongBao("Sửa món ăn không thành công");
                        }
                        else
                        {
                            thongBao("Đã sửa món ăn.");
                            layDanhSachMonAn();
                            hienThiMonAn();
                            lamMoi();
                        }
                    }
                    catch(Exception ex)
                    {
                        thongBao("Giá tiền và số lượng chỉ được nhập kí tự số!");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSuaMonAnActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(this.txtTimKiemMonAn.getText().trim().equals(""))
            thongBao("Vui lòng nhập vào ô tìm kiếm!");
        else
        {
            DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
            dsMonAn = dao.timKiemMonAn(this.txtTimKiemMonAn.getText().trim());
            hienThiMonAn();
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed


    private void layDanhSachLoaiMonAn()
    {
        dsLoaiMonAn.clear();
        DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
        dsLoaiMonAn = dao.layDanhSachLoaiMonAn();
    }
    
    private void hienThiLoaiMonAn()
    {
        DefaultListModel<String> dlm = new DefaultListModel<>();
        DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel<>();
        //listLoaiMonAn.removeAll();
        for(int i = 0; i < dsLoaiMonAn.size(); i++)
        {
            LoaiMonAn x = dsLoaiMonAn.get(i);
            dlm.add(i, (String)x.getTenLoaiMonAn());
            dcm.addElement((String)x.getTenLoaiMonAn());
        }
        listLoaiMonAn.setModel(dlm);
        cboMaLoaiMonAn.setModel(dcm);
    }
    
    private void layDanhSachMonAn()
    {
        dsMonAn.clear();
        DAO.QuanLyMonAn dao = new DAO.QuanLyMonAn();
        dsMonAn = dao.layDanhSachMonAn();
    }
    
    private void hienThiMonAn()
    {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Mã");
        dtm.addColumn("Tên");
        dtm.addColumn("Giá tiền");
        dtm.addColumn("Tồn kho");
        dtm.setNumRows(dsMonAn.size());
        for(int i = 0; i < dsMonAn.size(); i++)
        {
            MonAn x = dsMonAn.get(i);
            dtm.setValueAt(x.getMaMonAn(),i,0);
            dtm.setValueAt(x.getTenMonAn(), i, 1);
            dtm.setValueAt(x.getGiaTien(), i ,2);
            dtm.setValueAt(x.getSoLuong(),i,3);
        }
        this.tblMonAn.setModel(dtm);
    }
    
    private void lamMoi()
    {
        this.cboMaLoaiMonAn.setSelectedIndex(-1);
        this.txtMaMonAn.setText("");
        this.txtTenMonAn.setText("");
        this.txtGiaTien.setText("");
        this.txtSoLuong.setText("");
        this.txtTimKiemMonAn.setText("");
        layDanhSachMonAn();
        hienThiMonAn();
    }
    
    private void thongBao(String text)
    {
        JOptionPane.showMessageDialog(this, text, "Thông báo",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private int thongBaoXacNhan(String text)
    {
        return JOptionPane.showConfirmDialog(this, text, "Đắn đo không?", JOptionPane.YES_NO_OPTION);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaLoaiMonAn;
    private javax.swing.JButton btnSuaMonAn;
    private javax.swing.JButton btnThemLoaiMonAn;
    private javax.swing.JButton btnThemMonAn;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaLoaiMonAn;
    private javax.swing.JButton btnXoaMonAn;
    private javax.swing.JComboBox<String> cboMaLoaiMonAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listLoaiMonAn;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaMonAn;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenMonAn;
    private javax.swing.JTextField txtTimKiemMonAn;
    // End of variables declaration//GEN-END:variables
}
